/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.mock.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * TemplateSystemDO
 * database table: anymock_template_system
 * database table comments: TemplateSystem
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public class TemplateSystemDO implements java.io.Serializable {
    private static final long serialVersionUID = -5216457518046898601L;

    /**
     * 系统模板编号 		db_column: INNERID 
     */
    private String            innerid;
    /**
     * 通讯ID 		db_column: COMMUNICATION_ID 
     */
    private String            communicationId;
    /**
     * 系统模板内容，内容样子AssertAdaptor(aaaa)&AssertAdaptor(aaa) 		db_column: SYS_TEMPLATE 
     */
    private String            sysTemplate;
    /**
     * 唯一值说明 		db_column: MACTHDESCRIPTION 
     */
    private String            macthdescription;
    /**
     * 创建时间 		db_column: GMT_CREATE 
     */
    private Date              gmtCreate;
    /**
     * 修改时间 		db_column: GMT_MODIFIED 
     */
    private Date              gmtModified;

    public void setInnerid(String innerid) {
        this.innerid = innerid;
    }

    public String getInnerid() {
        return this.innerid;
    }

    public void setCommunicationId(String communicationId) {
        this.communicationId = communicationId;
    }

    public String getCommunicationId() {
        return this.communicationId;
    }

    public void setSysTemplate(String sysTemplate) {
        this.sysTemplate = sysTemplate;
    }

    public String getSysTemplate() {
        return this.sysTemplate;
    }

    public void setMacthdescription(String macthdescription) {
        this.macthdescription = macthdescription;
    }

    public String getMacthdescription() {
        return this.macthdescription;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Date getGmtModified() {
        return this.gmtModified;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("Innerid", getInnerid())
            .append("CommunicationId", getCommunicationId())
            .append("SysTemplate", getSysTemplate())
            .append("Macthdescription", getMacthdescription()).append("GmtCreate", getGmtCreate())
            .append("GmtModified", getGmtModified()).toString();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(getInnerid()).toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (this == obj)
            return true;
        if (obj instanceof TemplateSystemDO == false)
            return false;
        TemplateSystemDO other = (TemplateSystemDO) obj;
        return new EqualsBuilder().append(getInnerid(), other.getInnerid()).isEquals();
    }
}
