/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.mock.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * TemplateUserDO
 * database table: anymock_template_user
 * database table comments: TemplateUser
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 * 
 */
public class TemplateUserDO implements java.io.Serializable {
    private static final long serialVersionUID = -5216457518046898601L;

    /**
     * 模板ID 		db_column: ID 
     */
    private long              id;
    /**
     * 内部ID号 		db_column: INNERID 
     */
    private String            innerid;
    /**
     * 系统模板编号 		db_column: SYSTEM_INNERID 
     */
    private String            systemInnerid;
    /**
     * 绑定的用户模板ID，用于在一起显示，和业务无关、 		db_column: BIND_INNERID 
     */
    private String            bindInnerid;
    /**
     * 匹配值，通过该值找到该模板 		db_column: MATCHSTR 
     */
    private String            matchstr;
    /**
     * 是否为默认值。设置该值时，如果找不到，则默认走该渠道 		db_column: ISDEFAULT 
     */
    private String            isdefault;
    /**
     * 用户模板的名字 		db_column: TEMPLATE_NAME 
     */
    private String            templateName;
    /**
     * 使用的次数 		db_column: COUNT 
     */
    private int               count;
    /**
     * 用户ID 		db_column: USERNAME 
     */
    private String            username;
    /**
     * 创建时间 		db_column: GMT_CREATE 
     */
    private Date              gmtCreate;
    /**
     * 修改时间 		db_column: GMT_MODIFIED 
     */
    private Date              gmtModified;

    public void setId(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setInnerid(String innerid) {
        this.innerid = innerid;
    }

    public String getInnerid() {
        return this.innerid;
    }

    public void setSystemInnerid(String systemInnerid) {
        this.systemInnerid = systemInnerid;
    }

    public String getSystemInnerid() {
        return this.systemInnerid;
    }

    public void setBindInnerid(String bindInnerid) {
        this.bindInnerid = bindInnerid;
    }

    public String getBindInnerid() {
        return this.bindInnerid;
    }

    public void setMatchstr(String matchstr) {
        this.matchstr = matchstr;
    }

    public String getMatchstr() {
        return this.matchstr;
    }

    public void setIsdefault(String isdefault) {
        this.isdefault = isdefault;
    }

    public String getIsdefault() {
        return this.isdefault;
    }

    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    public String getTemplateName() {
        return this.templateName;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public int getCount() {
        return this.count;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return this.username;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Date getGmtModified() {
        return this.gmtModified;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("Id", getId()).append("Innerid", getInnerid())
            .append("SystemInnerid", getSystemInnerid()).append("BindInnerid", getBindInnerid())
            .append("Matchstr", getMatchstr()).append("Isdefault", getIsdefault())
            .append("TemplateName", getTemplateName()).append("Count", getCount())
            .append("Username", getUsername()).append("GmtCreate", getGmtCreate())
            .append("GmtModified", getGmtModified()).toString();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(getId()).toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        if (obj instanceof TemplateUserDO == false) {
            return false;
        }
        TemplateUserDO other = (TemplateUserDO) obj;
        return new EqualsBuilder().append(getId(), other.getId()).isEquals();
    }
}
