/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.mock.dal.dataobject;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * TemplateDetailDO
 * database table: anymock_template_detail
 * database table comments: TemplateDetail
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public class TemplateDetailDO implements java.io.Serializable {
    private static final long serialVersionUID = -5216457518046898601L;

    /**
     * 自动新增ID 		db_column: ID 
     */
    private long              id;
    /**
     * 内部ID号 		db_column: INNERID 
     */
    private String            innerid;
    /**
     * 模板ID的实际内容,从1开始，0是给assert使用 		db_column: DETAIL_VALUE 
     */
    private String            detailValue;
    /**
     * 模板的顺序 		db_column: DETAIL_SEQUENCE 
     */
    private int               detailSequence;
    /**
     * 创建时间 		db_column: GMT_CREATE 
     */
    private Date              gmtCreate;
    /**
     * 修改时间 		db_column: GMT_MODIFIED 
     */
    private Date              gmtModified;

    public void setId(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setInnerid(String innerid) {
        this.innerid = innerid;
    }

    public String getInnerid() {
        return this.innerid;
    }

    public void setDetailValue(String detailValue) {
        this.detailValue = detailValue;
    }

    public String getDetailValue() {
        return this.detailValue;
    }

    public void setDetailSequence(int detailSequence) {
        this.detailSequence = detailSequence;
    }

    public int getDetailSequence() {
        return this.detailSequence;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtCreate() {
        return this.gmtCreate;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Date getGmtModified() {
        return this.gmtModified;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("Id", getId()).append("Innerid", getInnerid())
            .append("DetailValue", getDetailValue()).append("DetailSequence", getDetailSequence())
            .append("GmtCreate", getGmtCreate()).append("GmtModified", getGmtModified()).toString();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(getId()).toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        if (this == obj)
            return true;
        if (obj instanceof TemplateDetailDO == false)
            return false;
        TemplateDetailDO other = (TemplateDetailDO) obj;
        return new EqualsBuilder().append(getId(), other.getId()).isEquals();
    }
}
