/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.mock.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * UserDO
 * database table: anymock_user
 * database table comments: User
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 */
public class UserDO implements java.io.Serializable {
    private static final long serialVersionUID = -5216457518046898601L;

    /**
     * 用户ID 		db_column: ID 
     */
    private long              id;
    /**
     * 用户名 		db_column: USERNAME 
     */
    private String            username;
    /**
     * 密码 		db_column: PASSWORD 
     */
    private String            password;
    /**
     * 是否为高级用户，是为TRUE 		db_column: SUPERUSER 
     */
    private String            superuser;

    public void setId(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUsername() {
        return this.username;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return this.password;
    }

    public void setSuperuser(String superuser) {
        this.superuser = superuser;
    }

    public String getSuperuser() {
        return this.superuser;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("Id", getId()).append("Username", getUsername())
            .append("Password", getPassword()).append("Superuser", getSuperuser()).toString();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder().append(getId()).toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        if (obj instanceof UserDO == false) {
            return false;
        }
        UserDO other = (UserDO) obj;
        return new EqualsBuilder().append(getId(), other.getId()).isEquals();
    }
}
