/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.mock.dal.ibatis;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.mock.dal.daointerface.CommunicationDAO;
import com.mock.dal.dataobject.CommunicationDO;

/**
 * CommunicationDAO
 * database table: anymock_communication
 * database table comments: Communication
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 * 
 */
public class IbatisCommunicationDAO extends SqlMapClientDaoSupport implements CommunicationDAO {

    /**
     * 
     * sql: 
     * <pre>select         id,       connect_type,       istransfer,       protocol_type,       charset,       uri,       description,       recv_data_type,       send_data_type,       properties,       max_counter,       gm_created,       gm_modified          from         anymock_communication</pre>
     */
    @SuppressWarnings("unchecked")
    public List<CommunicationDO> loadAll() throws DataAccessException {
        return getSqlMapClientTemplate().queryForList("anymock.Communication.loadAll", null);
    }

    /**
     * 
     * sql: 
     * <pre>insert      into         anymock_communication         (       id,       connect_type,       istransfer,       protocol_type,       charset,       uri,       description,       recv_data_type,       send_data_type,       properties,       max_counter,       gm_created,       gm_modified     )      values         (?,?,?,?,?,?,?,?,?,?,?,sysdate(),sysdate())</pre>
     */
    public java.lang.String insert(CommunicationDO communication) throws DataAccessException {
        if (communication == null) {
            throw new IllegalArgumentException("Can't insert a null data object into db.");
        }
        getSqlMapClientTemplate().insert("anymock.Communication.insert", communication);
        return communication.getId();
    }

    /**
     * 
     * sql: 
     * <pre>select         id,       connect_type,       istransfer,       protocol_type,       charset,       uri,       description,       recv_data_type,       send_data_type,       properties,       max_counter,       gm_created,       gm_modified          from         anymock_communication           where         id = ?</pre>
     */
    public CommunicationDO selectById(String id) throws DataAccessException {
        return (CommunicationDO) getSqlMapClientTemplate().queryForObject(
            "anymock.Communication.selectById", id);
    }

    /**
     * 
     * sql: 
     * <pre>select         id          from         anymock_communication           where         uri = ?</pre>
     */
    @SuppressWarnings("unchecked")
    public List<String> selectByMutiUrl(String uri) throws DataAccessException {
        return getSqlMapClientTemplate().queryForList("anymock.Communication.selectByMutiUrl", uri);
    }

    /**
     * 
     * sql: 
     * <pre>select         id          from         anymock_communication           where         uri = ?          and      connect_type = ?</pre>
     */
    public String selectByUrl(String uri, String connectType) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("uri", uri);
        param.put("connectType", connectType);
        return (String) getSqlMapClientTemplate().queryForObject(
            "anymock.Communication.selectByUrl", param);
    }

    /**
     * 
     * sql: 
     * <pre>delete      from         anymock_communication          where         id = ?</pre>
     */
    public int deleteByID(String id) throws DataAccessException {
        return getSqlMapClientTemplate().delete("anymock.Communication.deleteByID", id);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_communication      set         connect_type=?,       istransfer=?,       protocol_type=?,       charset=?,       uri=?,             recv_data_type=?,       send_data_type=?,       properties=?,       description=?,       max_counter=?,      gm_modified =sysdate()          where         id =?</pre>
     */
    public int updateByID(CommunicationDO communication) throws DataAccessException {
        if (communication == null) {
            throw new IllegalArgumentException("Can't update by a null data object.");
        }
        return getSqlMapClientTemplate().update("anymock.Communication.updateByID", communication);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_communication      set         connect_type =?,      gm_modified =sysdate()          where         id =?</pre>
     */
    public int updateConnectType(String connectType, String id) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("connectType", connectType);
        param.put("id", id);
        return getSqlMapClientTemplate().update("anymock.Communication.updateConnectType", param);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_communication      set         istransfer =?,      gm_modified =sysdate()          where         id =?</pre>
     */
    public int updateIstransfer(String istransfer, String id) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("istransfer", istransfer);
        param.put("id", id);
        return getSqlMapClientTemplate().update("anymock.Communication.updateIstransfer", param);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_communication      set         uri =?,      gm_modified =sysdate()          where         id =?</pre>
     */
    public int updateUri(String uri, String id) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("uri", uri);
        param.put("id", id);
        return getSqlMapClientTemplate().update("anymock.Communication.updateUri", param);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_communication      set         properties =?,      gm_modified =sysdate()          where         id =?</pre>
     */
    public int updateProperties(String properties, String id) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("properties", properties);
        param.put("id", id);
        return getSqlMapClientTemplate().update("anymock.Communication.updateProperties", param);
    }

}
