/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */

package com.mock.dal.ibatis;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.mock.dal.daointerface.TemplateDetailDAO;
import com.mock.dal.dataobject.TemplateDetailDO;

/**
 * TemplateDetailDAO
 * database table: anymock_template_detail
 * database table comments: TemplateDetail
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public class IbatisTemplateDetailDAO extends SqlMapClientDaoSupport implements TemplateDetailDAO {

    /**
     * 
     * sql: 
     * <pre>select         id,      innerid,           detail_value,           detail_sequence,           gmt_create,           gmt_modified          from         anymock_template_detail</pre>
     */
    @SuppressWarnings("unchecked")
    public List<TemplateDetailDO> loadAll() throws DataAccessException {
        return getSqlMapClientTemplate().queryForList("anymock.TemplateDetail.loadAll", null);
    }

    /**
     * 
     * sql: 
     * <pre>select         id,      innerid,           detail_value,           detail_sequence,          gmt_create,           gmt_modified                              from         anymock_template_detail          where         innerid=?          order by         detail_sequence</pre>
     */
    @SuppressWarnings("unchecked")
    public List<TemplateDetailDO> selectByInnerId(String innerid) throws DataAccessException {
        return getSqlMapClientTemplate().queryForList("anymock.TemplateDetail.selectByInnerId",
            innerid);
    }

    /**
     * 
     * sql: 
     * <pre>select         id,      innerid,           detail_value,           detail_sequence,           gmt_create,           gmt_modified           from         anymock_template_detail           where         id = ?</pre>
     */
    public TemplateDetailDO selectDetailById(Long id) throws DataAccessException {
        return (TemplateDetailDO) getSqlMapClientTemplate().queryForObject(
            "anymock.TemplateDetail.selectDetailById", id);
    }

    /**
     * 
     * sql: 
     * <pre>insert      into         anymock_template_detail         (        innerid,        detail_value,        detail_sequence,        gmt_create,        gmt_modified)          values         (?,?,?,sysdate(),sysdate())</pre>
     */
    public long insert(TemplateDetailDO templateDetail) throws DataAccessException {
        if (templateDetail == null) {
            throw new IllegalArgumentException("Can't insert a null data object into db.");
        }
        getSqlMapClientTemplate().insert("anymock.TemplateDetail.insert", templateDetail);
        return templateDetail.getId();
    }

    /**
     * 
     * sql: 
     * <pre>delete      from         anymock_template_detail          where         id = ?</pre>
     */
    public int deleteByID(Long id) throws DataAccessException {
        return getSqlMapClientTemplate().delete("anymock.TemplateDetail.deleteByID", id);
    }

    /**
     * 
     * sql: 
     * <pre>delete      from         anymock_template_detail          where         innerid = ?</pre>
     */
    public int deleteAllByInnerid(String innerid) throws DataAccessException {
        return getSqlMapClientTemplate().delete("anymock.TemplateDetail.deleteAllByInnerid",
            innerid);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_template_detail      set         detail_value =?,      gmt_modified =sysdate()          where         id =?</pre>
     */
    public int updateByID(String detailValue, Long id) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("detailValue", detailValue);
        param.put("id", id);
        return getSqlMapClientTemplate().update("anymock.TemplateDetail.updateByID", param);
    }

    /**
     * 
     * sql: 
     * <pre>update         anymock_template_detail      set         detail_sequence =?,      gmt_modified =sysdate()          where         id =?</pre>
     */
    public int updateSequence(Integer detailSequence, Long id) throws DataAccessException {
        Map<String, Object> param = new HashMap<String, Object>();
        param.put("detailSequence", detailSequence);
        param.put("id", id);
        return getSqlMapClientTemplate().update("anymock.TemplateDetail.updateSequence", param);
    }

}
