/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package com.mock.dal.daointerface;

import java.util.List;
import org.springframework.dao.DataAccessException;
import com.mock.dal.dataobject.TemplateDetailDO;

/**
 * TemplateDetailDAO
 * database table: anymock_template_detail
 * database table comments: TemplateDetail
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 *
 
 */
public interface TemplateDetailDAO {

    /**
     * 
     * sql:
     * <pre>select         id,      innerid,           detail_value,           detail_sequence,           gmt_create,           gmt_modified          from         anymock_template_detail</pre> 
     */
    public List<TemplateDetailDO> loadAll() throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>select         id,      innerid,           detail_value,           detail_sequence,          gmt_create,           gmt_modified                              from         anymock_template_detail          where         innerid=?          order by         detail_sequence</pre> 
     */
    public List<TemplateDetailDO> selectByInnerId(String innerid) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>select         id,      innerid,           detail_value,           detail_sequence,           gmt_create,           gmt_modified           from         anymock_template_detail           where         id = ?</pre> 
     */
    public TemplateDetailDO selectDetailById(Long id) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>insert      into         anymock_template_detail         (        innerid,        detail_value,        detail_sequence,        gmt_create,        gmt_modified)          values         (?,?,?,sysdate(),sysdate())</pre> 
     */
    public long insert(TemplateDetailDO templateDetail) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>delete      from         anymock_template_detail          where         id = ?</pre> 
     */
    public int deleteByID(Long id) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>delete      from         anymock_template_detail          where         innerid = ?</pre> 
     */
    public int deleteAllByInnerid(String innerid) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>update         anymock_template_detail      set         detail_value =?,      gmt_modified =sysdate()          where         id =?</pre> 
     */
    public int updateByID(String detailValue, Long id) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>update         anymock_template_detail      set         detail_sequence =?,      gmt_modified =sysdate()          where         id =?</pre> 
     */
    public int updateSequence(Integer detailSequence, Long id) throws DataAccessException;

}
