/*
 * Alipay.com Inc.
 * Copyright (c) 2004 - 2010 All Rights Reserved.
 * Powered By [rapid-generator]
 */
package com.mock.dal.daointerface;

import java.util.List;
import org.springframework.dao.DataAccessException;
import com.mock.dal.dataobject.UserDO;

/**
 * UserDAO
 * database table: anymock_user
 * database table comments: User
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * @author badqiu(zhongxuan)
 * 
 */
public interface UserDAO {

    /**
     * 
     * sql:
     * <pre>insert      into         anymock_user         (        username,        password,        superuser        )          values         (?,?,?)</pre> 
     */
    public long insert(UserDO user) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>select         id,         username,         password,         superuser          from         anymock_user</pre> 
     */
    public List<UserDO> loadAll() throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>select         password,        superuser           from         anymock_user           where         username =?</pre> 
     */
    public UserDO selectByName(String username) throws DataAccessException;

    /**
     * 
     * sql:
     * <pre>update         anymock_user      set         superuser = ?           where         username =?</pre> 
     */
    public int upSuperStatus(String superuser, String username) throws DataAccessException;

}
